BASE_URL = 'https://www.ebay.co.uk/'


MAIN_PAGE_TITLE = 'Electronics, Cars, Fashion, Collectibles, Coupons and More | eBay'
SEARCH_INPUT = 'Intel NUC'
SORT_DROP_DOWN = '.sort-menu-container > a:nth-child(1)'
LOWEST_PRICE = 'a[value="2"]'
BUY_PAGE_TITLE = ''
SEARCH_BOX = '#gh-ac'
SEARCH_BUTTON = '#gh-btn'
RESULTS_PAGE_TITLE = '| eBay'
SEARCH_RESULT_SELECTOR = '.rsHdr'
MEMORY = 'input#e1-59.cbx'
CONDITION = 'input[name="LH_ItemCondition"][aria-label="New"]'
BUY_NOW = '.small.cbx.btn.last_b'